column_names:
- Country
- '1970'
- '1971'
- '1972'
- '1973'
- '1974'
- '1975'
- '1976'
- '1977'
- '1978'
- '1979'
- '1980'
- '1981'
- '1982'
- '1983'
- '1984'
- '1985'
- '1986'
- '1987'
- '1988'
- '1989'
- '1990'
- '1991'
- '1992'
- '1993'
- '1994'
- '1995'
- '1996'
- '1997'
- '1998'
- '1999'
- '2000'
- '2001'
- '2002'
- '2003'
- '2004'
- '2005'
- '2006'
- '2007'
- '2008'
- '2009'
- '2010'
- '2011'
- '2012'
- '2013'
- '2014'
- '2015'
- '2016'
- '2017'
- '2018'
- '2019'
- '2020'
- '2021'
- '2022'
- '2023'
description: The dataset titled "GHG_by_sector_and_country_CO2_Agriculture" contains
  information on carbon dioxide (CO2) emissions from agriculture across various countries.
  The data columns represent a wide range of countries and regions, including Afghanistan,
  Argentina, the United States, and the EU27, among others. Each country has a corresponding
  value indicative of CO2 emissions, measured in a specific manner that appears to
  include several numerical entries along with instances of 'nan' indicating missing
  data. This dataset offers insights into agricultural emissions and can be essential
  for understanding global and regional contributions to greenhouse gas emissions.
id: df135eeb-ad7f-441a-a6db-2ff29a46fcf9
location: ../data/EDGAR_2024_GHG/GHG_totals_by_country.csv
name: GHG_totals_by_country
name_readable: []
product_names:
- test
- sum
- avg
- absolute
- relative
products:
- base_api: test
  description: test
  name: test
- base_api: http://127.0.0.1:5000/products/EDGAR_2024_GHG/sum
  description: sum
  name: sum
- base_api: http://127.0.0.1:5000/products/EDGAR_2024_GHG/avg
  description: avg
  name: avg
- base_api: http://127.0.0.1:5000/products/EDGAR_2024_GHG/absolute
  description: absolute
  name: absolute
- base_api: http://127.0.0.1:5000/products/EDGAR_2024_GHG/relative
  description: relative
  name: relative
row_names: []
