column_names:
- Aruba
- Afghanistan
- Angola
- Anguilla
- Albania
- "Cura\xE7ao"
- United Arab Emirates
- Argentina
- Armenia
- Antigua and Barbuda
- Australia
- Austria
- Azerbaijan
- Burundi
- Belgium
- Benin
- Burkina Faso
- Bangladesh
- Bulgaria
- Bahrain
- Bahamas
- Bosnia and Herzegovina
- Belarus
- Belize
- Bermuda
- Bolivia
- Brazil
- Barbados
- Brunei
- Bhutan
- Botswana
- Central African Republic
- Canada
- Switzerland and Liechtenstein
- Chile
- China
- "C\xF4te d\u2019Ivoire"
- Cameroon
- Democratic Republic of the Congo
- Congo
- Cook Islands
- Colombia
- Comoros
- Cabo Verde
- Costa Rica
- Cuba
- Cayman Islands
- Cyprus
- Czechia
- Germany
- Djibouti
- Dominica
- Denmark
- Dominican Republic
- Algeria
- Ecuador
- Egypt
- Eritrea
- Western Sahara
- Spain and Andorra
- Estonia
- Ethiopia
- Finland
- Fiji
- Falkland Islands
- France and Monaco
- Faroes
- Gabon
- United Kingdom
- Georgia
- Ghana
- Gibraltar
- Guinea
- Guadeloupe
- The Gambia
- Guinea-Bissau
- Equatorial Guinea
- Greece
- Grenada
- Greenland
- Guatemala
- French Guiana
- Guyana
- Hong Kong
- Honduras
- Croatia
- Haiti
- Hungary
- Indonesia
- India
- Ireland
- Iran
- Iraq
- Iceland
- Israel and Palestine, State of
- Italy, San Marino and the Holy See
- Jamaica
- Jordan
- Japan
- Kazakhstan
- Kenya
- Kyrgyzstan
- Cambodia
- Kiribati
- Saint Kitts and Nevis
- South Korea
- Kuwait
- Laos
- Lebanon
- Liberia
- Libya
- Saint Lucia
- Sri Lanka
- Lesotho
- Lithuania
- Luxembourg
- Latvia
- Macao
- Morocco
- Moldova
- Madagascar
- Maldives
- Mexico
- North Macedonia
- Mali
- Malta
- Myanmar/Burma
- Mongolia
- Mozambique
- Mauritania
- Martinique
- Mauritius
- Malawi
- Malaysia
- Namibia
- New Caledonia
- Niger
- Nigeria
- Nicaragua
- Netherlands
- Norway
- Nepal
- New Zealand
- Oman
- Pakistan
- Panama
- Peru
- Philippines
- Palau
- Papua New Guinea
- Poland
- Puerto Rico
- North Korea
- Portugal
- Paraguay
- French Polynesia
- Qatar
- "R\xE9union"
- Romania
- Russia
- Rwanda
- Saudi Arabia
- Serbia and Montenegro
- Sudan and South Sudan
- Senegal
- Singapore
- Saint Helena, Ascension and Tristan da Cunha
- Solomon Islands
- Sierra Leone
- El Salvador
- Somalia
- Saint Pierre and Miquelon
- "S\xE3o Tom\xE9 and Pr\xEDncipe"
- Suriname
- Slovakia
- Slovenia
- Sweden
- Eswatini
- Seychelles
- Syria
- Turks and Caicos Islands
- Chad
- Togo
- Thailand
- Tajikistan
- Turkmenistan
- Timor-Leste
- Tonga
- Trinidad and Tobago
- Tunisia
- "T\xFCrkiye"
- Taiwan
- Tanzania
- Uganda
- Ukraine
- Uruguay
- United States
- Uzbekistan
- Saint Vincent and the Grenadines
- Venezuela
- British Virgin Islands
- Viet Nam
- Vanuatu
- Samoa
- Yemen
- South Africa
- Zambia
- Zimbabwe
- EU27
- GLOBAL TOTAL
description: The dataset titled "GHG_totals_by_country" provides a comprehensive overview
  of greenhouse gas emissions measured in various countries, alongside aggregated
  numbers for international aviation and shipping. Each row presents data corresponding
  to specific nations, detailing their respective GHG emissions figures. The data
  fields include a wide array of countries, ranging from Aruba and Afghanistan to
  global totals, indicating substantial insights into emissions trends across different
  regions. This information is critical for understanding the environmental impact
  of different nations and for assessing global efforts to mitigate climate change.
id: null
location: ../data/data_products/EDGAR_2024_GHG/GHG_per_GDP_by_country.csv
name: GHG_per_GDP_by_country
name_readable: []
product_names:
- test
- sum
- avg
- absolute
- relative
products:
- base_api: test
  description: test
  name: test
- base_api: http://127.0.0.1:5000/EDGAR_2024_GHG/GHG_per_GDP_by_country/sum
  description: sum
  name: sum
- base_api: http://127.0.0.1:5000/EDGAR_2024_GHG/GHG_per_GDP_by_country/avg
  description: avg
  name: avg
- base_api: http://127.0.0.1:5000/EDGAR_2024_GHG/GHG_per_GDP_by_country/absolute
  description: absolute
  name: absolute
- base_api: http://127.0.0.1:5000/EDGAR_2024_GHG/GHG_per_GDP_by_country/relative
  description: relative
  name: relative
row_names: []
