name: sales_data_23
description: TODO
id: df135eeb-ad7f-441a-a6db-2ff29a46fcf9
location: ../data/EDGAR_2024_GHG/GHG_totals_by_country.csv
name_readable: []
product_names:
- sales_data_23
- customer_data_23
products:
- base_api: http://127.0.0.1:5000/products/Sales_Data/sales_data_23
  description: "The dataset titled \"sales_data_23\" contains sales transaction records from various shopping malls. It includes six columns: customer_id, category, quantity, price, invoice_date, and shopping_mall. The data features two entries, one for a toy purchase and another for clothing, detailing the quantity purchased, the total price, and the date of the transaction. The shopping malls involved are Cevahir AVM and Emaar Square Mall, providing insights into consumer behavior and sales trends in early 2023."
  name: sales_data_23
  columns:
    - invoice_no
    - customer_id
    - category
    - quantity
    - price
    - invoice_date
    - shopping_mall
  location: '../data/Sales_Data/sales_data_23.csv'
- base_api: http://127.0.0.1:5000/products/Sales_Data/customer_data_23
  description: "The dataset \"customer_data_23\" contains information about customers, specifically focusing on their gender, age, and payment method. It includes two entries, both of which are male customers aged 24 and 23 years old. The payment methods utilized by these customers are Cash and Credit Card, respectively. This data can be useful for analyzing customer demographics and payment preferences."
  name: customer_data_23
  columns:
    - customer_id
    - gender
    - age
    - payment_method
  location: '../data/Sales_Data/customer_data_23.csv'