Nodes:
  - Country:
      Properties:
        - name
        - countryCode
  - Region:
    - Properties:
      - name
  - Sector:
    - Properties:
      - name
  - Emission:
    - Properties:
      - name
  - Substance:
      - Properties:
          - name
          - abbr
relations:
  - inRegion:
      - From: Country
      - To: Region
  - regionContains:
      - From: Region
      - To: Country
  - hasSector:
      - From: Country
      - To: Sector
  - hasData:
      - From: Country
      - To: dataProduct
  - aboutCountry:
      - From: dataProduct
      - To: Country
  - hasEmission:
      - From: dataProduct
      - To: Emission
  - appearsInProduct:
      - From: Emission
      - To: dataProduct
  - concistsOfSubstance:
      - From: Emission
      - To: Substance
  - makesUpEmission:
      - From: Substance
      - To: Emission
      - To: Emission
